# Generated by Django 6.0.3 on 2026-03-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Used for static slider background', null=True, upload_to='sliders/')),
                ('video', models.FileField(blank=True, help_text='Optional, for video backgrounds', null=True, upload_to='sliders/videos/')),
                ('button_text', models.CharField(default='Enquire Now', max_length=100)),
                ('button_link', models.CharField(default='/contact-us/', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Hero Sliders',
                'ordering': ['order'],
            },
        ),
    ]
