# Generated by Django 6.0.3 on 2026-03-31 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_client_logo_alter_sitesettings_favicon_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavMenuItem',
        ),
    ]
