# Generated by Django 6.0.3 on 2026-03-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_navmenuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_email_notifications',
            field=models.BooleanField(default=True, verbose_name='Enable Email Notifications'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_sms_notifications',
            field=models.BooleanField(default=False, verbose_name='Enable SMS Notifications'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_whatsapp_notifications',
            field=models.BooleanField(default=False, verbose_name='Enable WhatsApp Notifications'),
        ),
    ]
