# Generated by Django 6.0.3 on 2026-03-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_customerorder_customerorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('packaging', 'Packaging'), ('ready_for_shipment', 'Ready for shipment'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('return_to_origin', 'Return to origin'), ('refund', 'Refund')], default='pending', max_length=30),
        ),
    ]
