# Generated by Django 6.0.3 on 2026-03-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_category_meta_description_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='homepage_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Homepage Display Order'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_on_homepage',
            field=models.BooleanField(default=False, verbose_name='Show on Homepage'),
        ),
    ]
